### ISSUE TITLE
Component could not be subdivided warning

### ISSUE THREAD

**Issue by mthelm85** [brendanstats/BayesianRecordLinkage.jl#2]
Hi,

This package looks really amazing! I tried running the example code with a couple of my own data sets and I keep getting the following Warning, which eventually leads to an error in the ```findfirst(penalties .> maximum(clusterThresholds))``` line:

```
┌ Warning: component with 15 rows and 296822 columns could not be subdivided, consider using a smaller increment.
└ @ BayesianRecordLinkage C:\Users\mthel\.julia\packages\BayesianRecordLinkage\8eUIu\src\clustering_functions.jl:465
```

I'm using ```thresholdInc = 0.0005``` and it still says it can't subdivide the component. When I lowered it to 0.0001 it ran for well over an hour before I finally shut it down. Any ideas? Thanks!!

**Comment by brendanCMUstats** [comment]
Hi Matt,

Just a quick overview of the procedure for context:
1) We start with some initial threshold on the weights and eliminate all of the record pairs below that threshold
2) We run the clustering algorithm the find the connected components
3) For any components that are larger than our predetermined size we increase the threshold (potentially excluding some additional record pairs) and repeat.

The warning is generated when incrementing the threshold causes a component to go from being too big according to the `maxsize` parameter (`npairscompThreshold ` variable in my example) to nonexistent (all of the weights are now below the threshold).  This is why the warning suggests picking a smaller increment. The hope is that a smaller increment will avoid excluding all of the record pairs within the component simultaneously.

In your case it looks like this is happening when a few records in your first dataset display very similar (or possibly identical) levels of similarity with a very large number of records in your second dataset.  This suggests a few options:

1. You could consider picking a larger `maxsize` but given the number of records in your second dataset that is maybe not a great option.
2. If you are not too worried about those 15 records then you can ignore the warning.
3. Potentially modify the weights that you are using for clustering.

One reason to consider 3, if you are following the procedure in the example, is that I have noticed that the tail behavior in the penalized likelihood estimates can be a little weird.  You could try subsetting the `pM` and `pU` values that go into the `maximum_weights_vector` function.  One way of doing this would be to look at the values in `penlikseq.nlinks` this will give you the number of links that are estimated using the parameterization stored in each row of `penlikseq.pM` and `penlikseq.pU`.  If some of the early or late values seem unreasonably low or high to you then excluding the corresponding rows of `penlikseq.pM` and `penlikseq.pU` might modify the weights in a way that is conducive to a better clustering.

Hope that helps! If none of these options work I can try to come up with some additional suggestions but they will probably end up being more problem dependent.

**Comment by brendanstats** [comment]
Hi Matt,

Just a quick overview of the procedure for context:
1) We start with some initial threshold on the weights and eliminate all of the record pairs below that threshold
2) We run the clustering algorithm the find the connected components
3) For any components that are larger than our predetermined size we increase the threshold (potentially excluding some additional record pairs) and repeat.

The warning is generated when incrementing the threshold causes a component to go from being too big according to the `maxsize` parameter (`npairscompThreshold ` variable in my example) to nonexistent (all of the weights are now below the threshold).  This is why the warning suggests picking a smaller increment. The hope is that a smaller increment will avoid excluding all of the record pairs within the component simultaneously.

In your case it looks like this is happening when a few records in your first dataset display very similar (or possibly identical) levels of similarity with a very large number of records in your second dataset.  This suggests a few options:

1. You could consider picking a larger `maxsize` but given the number of records in your second dataset that is maybe not a great option.
2. If you are not too worried about those 15 records then you can ignore the warning.
3. Potentially modify the weights that you are using for clustering.

One reason to consider 3, if you are following the procedure in the example, is that I have noticed that the tail behavior in the penalized likelihood estimates can be a little weird.  You could try subsetting the `pM` and `pU` values that go into the `maximum_weights_vector` function.  One way of doing this would be to look at the values in `penlikseq.nlinks` this will give you the number of links that are estimated using the parameterization stored in each row of `penlikseq.pM` and `penlikseq.pU`.  If some of the early or late values seem unreasonably low or high to you then excluding the corresponding rows of `penlikseq.pM` and `penlikseq.pU` might modify the weights in a way that is conducive to a better clustering.

Hope that helps! If none of these options work I can try to come up with some additional suggestions but they will probably end up being more problem dependent.

**Comment by mthelm85** [comment]
Thank you so much for the help, I really appreciate it!! I hope you keep up the amazing work!
