### ISSUE TITLE
example.jl throws error 

### ISSUE THREAD

**Issue by resteorts** [brendanstats/BayesianRecordLinkage.jl#7]
julia> julia example.jl 
ERROR: syntax: extra token "example" after end of expression
Stacktrace:
 [1] top-level scope at REPL[18]:0

**Comment by brendanstats** [comment]
Resolved by 4b7f1a61a0a0d0a41eca87d53b94391975b3d062 and 1e00272baa5a65a4007f05c8ac31ad27a5593cca
