### ISSUE TITLE
ordArray function in example.jl throws error 

### ISSUE THREAD

**Issue by resteorts** [brendanstats/BayesianRecordLinkage.jl#8]
julia> for jj in 1:nB, ii in 1:nA
           ordArray[ii, jj, 1] = levOrd(dataA[ii, gnameInd], dataB[jj, gnameInd])
           ordArray[ii, jj, 2] = levOrd(dataA[ii, fnameInd], dataB[jj, fnameInd])
           ordArray[ii, jj, 3] = boolOrd(dataA[ii, ageInd], dataB[jj, ageInd])
           ordArray[ii, jj, 4] = boolOrd(dataA[ii, occupInd], dataB[jj, occupInd])
       end

ERROR: MethodError: no method matching compare(::Levenshtein, ::String, ::String)
Closest candidates are:
  compare(::Any, ::Any, ::Union{DamerauLevenshtein, Jaro, Levenshtein, RatcliffObershelp, StringDistances.QGramDistance, StringDistances.Normalize, Partial, TokenMax, TokenSet, TokenSort, Winkler}; min_score) at /Users/beka/.julia/packages/StringDistances/VfSRi/src/StringDistances.jl:25
Stacktrace:
 [1] levOrd(::String, ::String) at ./REPL[13]:2
 [2] top-level scope at ./REPL[18]:2

Remark: No errors thrown before this.

**Comment by brendanstats** [comment]
Resolved by 1e00272baa5a65a4007f05c8ac31ad27a5593cca, `compare()` and `evaluate()` functions from the StringDistances package do not accept arguments in the same order. Note: it looks like the previous version was correct under version 0.3.2 of StringDistances.jl but fails to run under more recent versions.
